lib/beacon/live_admin/components.ex
lib/beacon/live_admin/live/layout_editor_live/form_component.ex
lib/beacon/live_admin/live/page_editor_live/edit.ex
lib/beacon/live_admin/live/page_editor_live/form_component.ex
lib/beacon/live_admin/live/page_editor_live/variants.ex
lib/beacon/live_admin/page_builder.ex
lib/beacon/live_admin/web.ex

Depends on https://github.com/BeaconCMS/beacon/pull/312

Reuse template_error/1 and fix changeset :action

---

lib/beacon/live_admin/live/page_editor_live/variants.ex

Close html p tag

---

lib/beacon/live_admin/content.ex
lib/beacon/live_admin/live/component_editor_live/index.ex
mix.lock
test/beacon/live_admin/live/component_editor_live/index_test.exs

PR for https://github.com/BeaconCMS/beacon_live_admin/issues/45
I think I also need to update `Content.list_components` in `Beacon` to support filtering.

Component search

---

lib/beacon/live_admin/live/layout_editor_live/revisions.ex
lib/beacon/live_admin/live/page_editor_live/revisions.ex

Follow up to #53 so the links are displayed on the revisions tab

Add resource links to layout revisions

---

lib/beacon/live_admin/components/admin_components.ex
lib/beacon/live_admin/live/component_editor_live/form_component.ex
lib/beacon/live_admin/live/layout_editor_live/form_component.ex
lib/beacon/live_admin/live/layout_editor_live/meta_tags.ex
lib/beacon/live_admin/live/layout_editor_live/resource_links.ex
lib/beacon/live_admin/live/layout_editor_live/revisions.ex
lib/beacon/live_admin/live/page_editor_live/event_handlers.ex
lib/beacon/live_admin/live/page_editor_live/form_component.ex
lib/beacon/live_admin/live/page_editor_live/meta_tags.ex
lib/beacon/live_admin/live/page_editor_live/revisions.ex
lib/beacon/live_admin/live/page_editor_live/schema.ex
lib/beacon/live_admin/live/page_editor_live/variants.ex

Display flash message (feedback) on actions

---

assets/svelte/components/PageWrapper.svelte

That is virtually never what the user would want.

Prevent layout links to navigate the user to a different page

---

assets/svelte/components/PageAstNode.svelte
assets/svelte/types.ts

https://github.com/BeaconCMS/beacon_live_admin/assets/265339/b2c2fd7c-fe69-4e1c-a42c-315fa3465de2

Preview where the dragged element is going to land and how it is going to look

---

assets/svelte/components/PageAstNode.svelte
assets/svelte/components/PagePreview.svelte
assets/svelte/components/PageWrapper.svelte
assets/svelte/components/PropertiesSidebar.svelte
assets/svelte/components/SidebarSection.svelte
assets/svelte/components/UiBuilder.svelte
assets/svelte/stores/live.ts
assets/svelte/types.ts
assets/svelte/utils/ast-manipulation.ts

https://github.com/BeaconCMS/beacon_live_admin/assets/265339/708f61c9-d177-40cb-a7a1-14026b4259a7

Allow edition using content editable

---

lib/beacon/live_admin/live/media_library_live/index.ex

sort by media type

---

assets/svelte/components/PropertiesSidebar.svelte
assets/svelte/components/SidebarSection.svelte

This allows to add any attribute to any element. It's up to the user to know what attributes are valid.

Allow arbitrary attributes

---

assets/svelte/utils/drag-helpers.ts

The new detecting algorithm looks at the position of the siblings to see if they flow vertically or horizontally.

[Bugfix] Better detect horizontal/vertical flow for drag and drop

---

assets/svelte/components/SelectedElementFloatingMenu/DragMenuOption.svelte

IMO this feels nicer, but it can be tweaked further if necessary.

Better detect overlapping when dragging elements to reorder

---

.github/workflows/ci.yml
assets/svelte/components/PageWrapper.svelte
assets/svelte/components/SelectedElementFloatingMenu/DragMenuOption.svelte

https://github.com/BeaconCMS/beacon_live_admin/pull/245#issuecomment-2353388933

CI - auto format

---

assets/svelte/components/PageAstNode.svelte
assets/svelte/components/SelectedElementFloatingMenu/DragMenuOption.svelte
assets/svelte/stores/page.ts
assets/svelte/utils/drag-helpers.ts

This should bring no changes, just simplifying logic.
If you test this, no news is good news.

Prepare for X and Y dragging. Simplify logic

---

assets/svelte/components/PageAstNode.svelte

[BUGFIX] Visual editor stops working after selecting eex blocks

---

assets/svelte/components/PropertiesSidebar.svelte
assets/svelte/components/SidebarSection.svelte

Fixes https://github.com/BeaconCMS/beacon_live_admin/issues/252

[BUGFIX] Fix sidebar operations for eex_block

---

assets/svelte/components/PropertiesSidebar.svelte

[BUGFIX] Pressing enter after changing an attr on sidebar makes the page unresponsive

---

assets/svelte/components/PageAstNode.svelte
assets/svelte/components/PageWrapper.svelte
assets/svelte/components/SelectedElementFloatingMenu.svelte
assets/svelte/components/SelectedElementFloatingMenu/DragMenuOption.svelte
assets/svelte/utils/drag-helpers.ts

https://github.com/user-attachments/assets/2b18e010-19c3-400f-9cd5-a6ef3dfb5cc4

[Bugfix] Fix drag and delete floating button for eex AstNodes

---

assets/svelte/components/SelectedElementFloatingMenu/DragMenuOption.svelte
assets/svelte/utils/drag-helpers.ts

Closes #246
https://github.com/user-attachments/assets/8c58d929-947c-4bcb-82f1-2408a8884389

Improve overlap detection

---

assets/svelte/components/SelectedElementFloatingMenu/DragMenuOption.svelte
assets/svelte/utils/drag-helpers.ts

Improved the drag and drop, specially bidirectional drag and drop.
https://github.com/user-attachments/assets/909a065a-896b-4ce7-b31d-43b6b283ff73

Improve bidirectional drag and drop

---

lib/beacon/live_admin/live/media_library_live/show_component.ex

Useful to copy and paste into the Visual Editor, on the .image component

Media - display file name

---

lib/beacon/live_admin/cluster.ex

Reverts BeaconCMS/beacon_live_admin#307

Revert "fix: enable remote node beacon autoload"

---

lib/beacon/live_admin/components/station_ui/html.ex
lib/beacon/live_admin/components/station_ui/html/accordion.ex
lib/beacon/live_admin/components/station_ui/html/avatar.ex
lib/beacon/live_admin/components/station_ui/html/banner.ex
lib/beacon/live_admin/components/station_ui/html/button.ex
lib/beacon/live_admin/components/station_ui/html/card.ex
lib/beacon/live_admin/components/station_ui/html/footer.ex
lib/beacon/live_admin/components/station_ui/html/form.ex
lib/beacon/live_admin/components/station_ui/html/icon.ex
lib/beacon/live_admin/components/station_ui/html/input.ex
lib/beacon/live_admin/components/station_ui/html/modal.ex
lib/beacon/live_admin/components/station_ui/html/navbar.ex
lib/beacon/live_admin/components/station_ui/html/notification_badge.ex
lib/beacon/live_admin/components/station_ui/html/pagination.ex
lib/beacon/live_admin/components/station_ui/html/spinner.ex
lib/beacon/live_admin/components/station_ui/html/status_badge.ex
lib/beacon/live_admin/components/station_ui/html/tab_group.ex
lib/beacon/live_admin/components/station_ui/html/table_cell.ex
lib/beacon/live_admin/components/station_ui/html/table_header.ex
lib/beacon/live_admin/components/station_ui/html/tag.ex
lib/beacon/live_admin/components/station_ui/html/toast.ex
lib/beacon/live_admin/components/station_ui/html/toolbar.ex
lib/beacon/live_admin/components/station_ui/html/tooltip.ex
lib/beacon/live_admin/components/visual_editor/id_control.ex
lib/beacon/live_admin/components/visual_editor/name_value_control.ex
lib/beacon/live_admin/components/visual_editor/properties_sidebar_component.ex

Remove StationUI and VisualEditor components from docs

---

CHANGELOG.md
lib/beacon/live_admin/live/event_handler_editor_live/index.ex

[Event Handlers] Fix event_params in "variables available" message

---

lib/beacon/live_admin/components/visual_editor/components/input_with_units.ex
lib/beacon/live_admin/components/visual_editor/properties_sidebar_component.ex
lib/beacon/live_admin/components/visual_editor/size_control.ex
lib/beacon/live_admin/components/visual_editor/typography_control.ex
lib/beacon/live_admin/visual_editor/css/size.ex

Add sidebar section to control the size of the element
