BeaconCMS/beacon_live_admin

lib/beacon/live_admin/live/page_editor_live/revisions.ex

Add a "Variants" section to each revision/snapshot on the "Revisions" page
* Create a `.revision` function component to simplify the template
* Replace `Enum.with_index` with a CSS-only solution for displaying "Latest" tag on the first event
* Add table to `.revision` component for listing all published variants
* Add a modal to main `render` to display variant template
* Modal opens when the variant link is clicked

Add variants to revisions page

---

lib/beacon/live_admin/live/page_editor_live/variants.ex

After closing a modal via any method besides the "Cancel" button, the "show modal" assign is not reset, so the modal cannot be opened again until a full page reload
Use `on_cancel` attr to trigger the cancel event whenever the modal is closed

Reset modal show assign on modal close

---

lib/beacon/live_admin/live/page_editor_live/revisions.ex

* Extract tables into function components which hide headers when there are no rows
* Re-use existing modal to show event handler code
* Ensure code editors use the correct language

Add event handlers to revisions page

---

lib/beacon/live_admin/page_builder.ex
lib/beacon/live_admin/page_live.ex

It can be added as:
```elixir
def menu_link(_, :index), do: {:root, "Layouts", "hero-face-smile"}
```
Note that all pages (index, edit, etc) are supposed to be declared as above to render the icons on all paths.

Add support for displaying hero icons in the menu

---

.github/workflows/ci.yml
lib/beacon/live_admin/application.ex
lib/beacon/live_admin/cluster.ex
lib/beacon/live_admin/live/home_live.ex
lib/beacon/live_admin/page_live.ex
mix.lock
test/beacon/live_admin/cluster_test.exs
test/support/cluster.ex
test/test_helper.exs

Register sites using :pg on init and rely on its state to find nodes
Fix issues on net split

Improve cluster communcation

---

assets/svelte/stores/page.ts

Not all element have an AST content, so this function sometimes broke.

Bugfix on recursive element find 

---

assets/svelte/components/PropertiesSidebar.svelte

Self_close is not an editable attribute, is just for internal use

---

assets/svelte/components/PropertiesSidebar.svelte

This is less confusing than the old one, that looked like an "undo" icon.

Improve level up icon

---

lib/beacon/live_admin/live/layout_editor_live/resource_links.ex
test/beacon/live_admin/live/layout_editor_live/edit_test.exs

Resolves #103 
Resource links were broken because the logic in `coerce_resource_link_params/1` wasn't returning the correct data type.
```elixir
%{"resource_links" => [
%{"rel" => "rel1", "href" => "href1"},
%{"rel" => "rel2", "href" => "href2"}
]}
```
```elixir
%{"resource_links" => %{"href" => "href2", "rel" => "rel2"}}
```

Fix resource links form params

---

assets/svelte/components/PagePreview.svelte

Fixes #155 
After dropping a component into the page we didn't reset the drag and drop state, causing the sidebar to never open again as it thought we were still dragging a component.

Set dragged object to null after a drop

---

assets/svelte/components/PropertiesSidebar.svelte
assets/svelte/components/SidebarSection.svelte

Closes #152
The field is not a texarea, which shows to rows by default but can be resize to any size by the user.
Also, since now it's possible to edit in place most of the texts, this text input is not used so often.

Resize Content input text to fit more text

---

README.md

Using unqualified node names doesn't work on some versions of OS X, this is the simplest way to ensure compatibility without asking users to alter their hostsfile

Update node connection instructions in README.md

---

lib/beacon/live_admin/live/page_editor_live/form_component.ex
lib/beacon/live_admin/live/page_editor_live/new.ex

https://github.com/BeaconCMS/beacon_live_admin/assets/13787741/89b0afe9-7c15-45b6-9b7d-cd67683fd18c

Page Builder - enable the editor on New pages

---

lib/beacon/live_admin/content.ex
lib/beacon/live_admin/live/component_editor_live/edit.ex
lib/beacon/live_admin/live/component_editor_live/form_component.ex
lib/beacon/live_admin/live/component_editor_live/new.ex
lib/beacon/live_admin/live/component_editor_live/slot_attr.ex
lib/beacon/live_admin/live/component_editor_live/slots.ex

- Remove Example input text field from Component form;
- Add a CodeEditor field to body and template in the Component form;
- When clicking "New Slot", creates a Slot for the component with unique name;
- Add changeset validations - Unique name for ComponentAttr, ComponentSlot and ComponentSlotAttr
before:
after:

Add code_editor field for Component body and example fields

---

assets/svelte/components/ComponentsSidebar.svelte

- Add the Section Component Category in ComponentsSidebar (it was necessary, otherwise the word 'undefined' appered instead of the word 'Section')

Add new component category in ComponentsSidebar

---

lib/beacon/live_admin/live/media_library_live/index.ex

It appears that agent authorization was removed in #189, but several components still have references to an `@agent` assigns that no longer exists. This PR removes those references and fixes the reference to the missing key/value in the assigns. This seems to make the upload media components work again.

Remove defunct reference to agent assigns

---

assets/svelte/components/ComponentsSidebar.svelte
assets/svelte/components/PagePreview.svelte
assets/svelte/stores/dragAndDrop.ts

Closes #205 : Dropping a dragged object into invalid target breaks the component sidebar
After dropping any element on an invalid target, the component sidebar was staying disabled. 
* Making sure that the drag state is being reset, even after dropping on an invalid target
* Add a generic `resetDrag` function so we can trigger that from different places, and for future improvements keep the logic of resetting the state in one place
Before, it was just returning from the `drop` even handler when the target was invalid, but the `draggedObject` was still set. Therefore the app still thinks it's in drag mode, and disabling the component sidebar.
1. Open any of the page editors
2. Use the sidebar to drag a component (any will work)
3. Drop the component on the most outer wrapper (the fake …

Issue 205: Reset drag states when dropping, even on invalid targets

---

assets/svelte/components/PageAstNode.svelte

Closes #203: Improve target placement
When dragging in a new element, the placeholder starts flashing. That's because having the cursor enter the placeholder triggers a `dragLeave` on the parent and therefor doesn't capture the action as still wanting to drop something in that parent.
* Disable `dragLeave` trigger on drag placeholder (or basically any pointer/drag events, because the placeholder is just a visual placeholder and should be handled as a non-existing element. The events are still being triggered on the parent as expected. 
1. Edit a Page
2. Drag a new element into the visual editor
3. Make sure to drag over it's own placeholder
4. Verify: dragging over the placeholder doesn't remove it or cause any disturbances in how the placeholder is being displayed
Before|After
---|---

Issue 203: Disable dragLeave trigger on drag placeholder

---

assets/svelte/components/SelectedElementFloatingMenu/DragMenuOption.svelte

Before this change, when sibling elements were reordered with drag and drop, the selected element changed after the drop.
The root cause is that the currently selected elements is stored with a "path" (e.g. `1.4.3.0.2`, meaning the "the third, child of the first child of the fourth child o the fifth child of the second element in the page"), and the last number of that path has to be updated to reflect the new position of the dropped element among its siblings.

[Bufgix] After sorting elements with drag and drop, the same items should stay selected

---

assets/svelte/components/SelectedElementFloatingMenu/DragMenuOption.svelte

This prevents the item lagging behind the mouse

Disable transitions on the item being dragged

---

assets/svelte/components/PagePreview.svelte
assets/svelte/components/PageWrapper.svelte
assets/svelte/components/SelectedElementFloatingMenu/DragMenuOption.svelte
assets/svelte/components/UiBuilder.svelte
assets/svelte/stores/page.ts

This also fixes a bug when leaving the visual editor and returning to it with one selected element. Now the stores get reset when the UIEditor is destroyed.
Closes #224

[Bugfix] Allow to drop elements on the root

---

CHANGELOG.md
lib/beacon/live_admin/page_builder/table.ex

Skip pagination when beacon_page.table is not available

Close #204

---

lib/beacon/live_admin/live/page_editor_live/form_component.ex
lib/beacon/live_admin/live/page_editor_live/index.ex

Fix a race condition between updating the AST from client/server and saving the changes made on the template.
Since we have 2 distinct events: one to update the AST and another to actually save the changes, on an env with high latency when one makes a change on the visual editor and hit Save Change there could a race condition that would save the old template because it wasn't updated yet.
So we need to use another assign that is guaranteed to be updated before the save event actually happens.
Close #226

[Visual Editor] Fix a race condition between update AST and save change events

---

assets/svelte/components/PageAstNode.svelte
assets/svelte/components/SelectedElementFloatingMenu/DragMenuOption.svelte

One of the bug was not accounting that not all nodes you select have a `content` property. `eex` expressions don't.
The other bug that made the entire page go blank was caused because when a page's DOM estructure, sometimes it's not possible to get the "grandfather" element of an element because there isn't one. However in those situations we can get the DOM Fragment at the root of the web-component.

Fixes two editor bugs that slipped through

---

assets/svelte/components/PageWrapper.svelte

When the elements of the layout and the elements of the page share the same wrapper, positioning calculations are broken.
Adds a wrapper with `display: contents` that doesn't have any effect on CSS, but still allows to tell apart which items belong to the page and which ones belong to the surounding layout.
https://github.com/user-attachments/assets/e7d28020-8c45-46ad-a085-5e8ec57074a4

Fixes the calculations of the positions when pages have no wrapper

---

assets/svelte/components/PageAstNode.svelte
assets/svelte/components/PageWrapper.svelte
assets/svelte/components/SelectedElementFloatingMenu.svelte
assets/svelte/components/SelectedElementFloatingMenu/DragMenuOption.svelte
assets/svelte/stores/page.ts
assets/svelte/utils/drag-helpers.ts

Quite often, elements have wrappers with no padding. When there's no padding, it's not possible to select the wrapper of an element because the click always lands on the children. 
Until now, it was possible to click the "Go one level up" button to traverse the tree towards the root, but it was incovenient.
Now, when an element is selected to be dragged, the parent element also shows a handle button to drag it. This makes dragging much more convenient, as there's less steps involved in selecting and dragging the element you intended.
https://github.com/user-attachments/assets/cca176e1-d7c0-4e8b-8928-0fa7f258d82a

Allow to drag the parent of the selected element

---

assets/svelte/components/SelectedElementFloatingMenu/DragMenuOption.svelte

This is both a bugfix and a feature.
I noticed that the drag and drop behaved weird sometimes, and it took a moment to notice that it happened when dragging elements that have html comments in between them.
This was because the index of the element being dragged to/into didn't match those in the AST tree, because the AST tree contains html comments but  the drag and drop ignores non-renderable elements (which makes sense, as you can't drop between an element and a comment).
And also, even when it worked, comments weren't dragged and more often that not they ended being quite useless as they were next to the wrong element.
This fixes the bug while adding a new feature that I call "sticky comments". That is, when you drag an element, any comment directly preceding the dragged elements get …

Drag & drop: Sticky comments

---

lib/beacon/live_admin/router.ex
test/beacon/live_admin/live/live_data_editor_live/index_test.exs
test/beacon/live_admin/live/page_editor_live/index_test.exs

Every path, including assets paths, are relative to the base url plus the admin prefix and tenant (site name).
To resolve the path we fetch the router from conn/socket so we don't need to know about the host app endpoint.
Ref https://github.com/BeaconCMS/beacon_live_admin/issues/272

chore: remove router helper `beacon_live_admin_url/4`

---

dev.exs
lib/beacon/live_admin.ex
lib/beacon/live_admin/application.ex
lib/beacon/live_admin/config.ex
lib/beacon/live_admin/errors.ex
lib/beacon/live_admin/instance_supervisor.ex
lib/beacon/live_admin/registry.ex
lib/beacon/live_admin/router.ex
test/beacon/live_admin/router_test.exs

Just the skeleton for now but it will hold some config like `:sites` (filter managed sites).
Soft-breaking change: added required `:name` opt in `beacon_live_admin/2`

Introduce `Beacon.LiveAdmin.Config`

---

.github/workflows/ci.yml

`maj.min` format only allowed with `~>` prefix

Fix `phoenix-live-view` version format

---

lib/beacon/live_admin/live/page_editor_live/form_component.ex
test/beacon/live_admin/live/page_editor_live/new_test.exs

Using `push_patch` bypasses some of the expected setup which is normally done when navigating to the page editor.  Switching to `push_navigate` will still avoid a full page reload but properly mounts the page

Fix draft page creation bug

---

lib/mix/tasks/beacon_live_admin.install.ex

- warn when Igniter is not available
- warn when running in the root of an Umbrella app

chore(task): safe guard install task
